### PR TITLE
Move top-level crates into crates/ folder

### PR DESCRIPTION
**Pull request by XAMPPRocky**
Implements the crates part of #170

### CODE REVIEW

**Review by khyperia — APPROVED** [review]
Ah, I just noticed the links in `docs/src/introduction.md` are rather out of date, they used to link to folders in the repo, but... the rendered doc isn't even in the repo anymore! Can fix this now or later.

**Comment by XAMPPRocky** [comment]
@khyperia Updated

**Comment by repi** [comment]
This has to be rebased/merged with latest `main` a lot of diffs from it. May be easiest to just do re-do it quickly and get it in? As things are moving fast it is hard to have larger refactors in PRs

**Comment by XAMPPRocky** [comment]
Welp, somehow that force push closed the PR. I'll open a new one. I was waiting for #109 to land since moving the crates updates the examples.

**Pull request closed without merging**
