### PR TITLE
Enable builtins.

### PR DESCRIPTION
**Pull request by dvc94ch**

### CODE REVIEW

**Comment by eddyb** [comment]
Can you try adding tests for these? I thought they couldn't work for now.

**Comment by dvc94ch** [comment]
They seem to work fine. Any reason why you think they shouldn't?

**Comment by dvc94ch** [comment]
Is there an example of an existing builtin test somewhere?

**Comment by expenses** [comment]
See: https://github.com/EmbarkStudios/rust-gpu/pull/789 (I followed the git blame)

> In discord, it was pointed out that `#[spirv(workgroup_size)]` is broken - the decoration applies to a constant, not a variable, and it specifies the workgroup size, it's not provided with the workgroup size. (A subsequent discussion also showed that WorkgroupSize in SPIR-V is just plain broken with multi-entry-point shaders - but the LocalSize(Id) execution mode is a replacement for its behavior)

**Comment by dvc94ch** [comment]
ok `workgroup_size` might be broken, realized I wasn't actually using it. but I think we went over this in https://github.com/EmbarkStudios/rust-gpu/issues/841, `subgroup_local_invocation_id` should be supported as it has the following enabling capabilities: Kernel, GroupNonUniform, SubgroupBallotKHR.

**Comment by dvc94ch** [comment]
Let me know if you want me to drop the example.

**Review by eddyb — APPROVED** [review]
[Looking at the Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-builtin-variables-sgli) (since SPIR-V fails to document it), looks like `SubgroupLocalInvocationId` does indeed go on a variable.

(Whereas [for `WorkgroupSize` it mentions "constants"](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-builtin-variables-warpidnv) - though technically ambiguous/a misuse of "variable")

**Pull request merged**
