### PR TITLE
Make maintainers explicit with CODEOWNERS

### PR DESCRIPTION
**Pull request by lpil**
Hello!

We're making maintainers explicit. I've guessed the maintainers here, let me know if this is not right. Thanks!

### CODE REVIEW

**Comment by termhn** [comment]
I think the CODEOWNERS structure should look something like this (not sure if @VZout wants to be included as an examples/ owner or not, and you could probably put @khyperia as one of the owners on every one of these categories if she wants :P)

```
* @khyperia

crates/* @khyperia @eddyb 

examples/* @khyperia @termhn @VZout(?)

docs/* @XAMPPRocky
*.md @XAMPPRocky
```

**Comment by lpil** [comment]
Wonderful, thank you so much @termhn ! I've updated this PR with your suggestion.

**Comment by khyperia** [comment]
Linking https://github.com/EmbarkStudios/rust-gpu/issues/161 because this will close that issue

**Comment by lpil** [comment]
@khyperia Erin is off for a month so we won’t be able to get a review from her. Is there anything else to do here or can we merge?

**Comment by khyperia** [comment]
rrright, yes, sorry, completely forgot about that!

**Review by khyperia — APPROVED** [review]

**Comment by lpil** [comment]
Thank you everyone!! 💜

**Pull request merged**
