### PR TITLE
Fix Location calculation for arrays in entrypoint interface

### PR DESCRIPTION
**Pull request by Arc-blroth**
This PR fixes the calulation for Location decorations on array entrypoint parameters.

Both Vulkan ([spec][2]) and MLSL ([page 44 of the spec][3]) specify that array elements must take up consecutive locations, one for each element. Currently however, rust-gpu will always allocate 1 Location per entrypoint parameter, meaning that this code ([playground link][1]):
```rust
#[spirv(vertex)]
pub fn main_vs(
    data: Input<[f32; 4]>,
    more_data: Input<[f32; 4]>,
    mut out_data: Output<[f32; 4]>,
) {
```
will generate invalid SPIRV:
```
OpEntryPoint Vertex %1 "main_vs" %data %more_data %out_data
OpName %data "data"
OpName %more_data "more_data"
OpName %out_data "out_data"
OpDecorate %_arr_float_uint_4 ArrayStride 4
OpDecorate %data Location 0
OpDecorate %more_data Location 1
OpDecorate %out_data Location 0
```
since data and more_data have overlapping locations.

I'm not exactly that familiar with rustc and rustc_codegen_spirv, so there might be a better way to tell if an entrypoint parameter maps to a SPIRV array type than inspecting the generated type - please review :)

[1]: http://shader-playground.timjones.io/f15e88399b8c03dc131f7f758d53a1c2/vkspec.html#interfaces-iointerfaces-locations
[2]: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#interfaces-iointerfaces-locations
[3]: https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

### CODE REVIEW

**Review by XAMPPRocky — CHANGES_REQUESTED** [review]
Thank you for your PR! This looks good to me, can you also add two tests? One to ensure that the behaviour works, and one that generates the `invalid entry param type` error? You can see similar tests in `tests/ui`.

**Comment by Arc-blroth** [comment]
@eddyb pointed out that this PR is essentially blocked on #443 - I'll update this PR after that one is merged.

**Comment by Arc-blroth** [comment]
Sorry for taking so long, but I've updated to HEAD and added a test for fixing array locations. (The CI seems to be failing because of commits that don't have any relationship to this PR)

**Review by XAMPPRocky — APPROVED** [review]
LGTM!

**Review by khyperia — APPROVED** [review]
LGTM, just adding a note to our future selves that this is incomplete, the vulkan spec says:

> 64-bit three- and four-component vectors consume two consecutive locations.

so we'll need to fix that too eventually (not needed in this PR).

**Comment by khyperia** [comment]
Closing this for inactivity, if you'd like to revive this, please do!

**Pull request closed without merging**
