### PR TITLE
Refactor attributes and add descriptor_set/binding

### PR DESCRIPTION
**Pull request by khyperia**
Whoof, this turned out bigger than expected. A lot of it is necessary refactoring to clean things up, though, not the actual adding of descriptor_set/binding.

Could someone try out this branch on a shader and try setting a uniform? I haven't tested it with `example-runner` since I'm not sure of the arcane vulkan shenanigans needed to bind a uniform on the CPU side.

The syntax looks like this:

```rust
pub fn main_fs(
    input: Input<Vec4>,
    #[spirv(descriptor_set = 2, binding = 5)] uni: Uniform<Vec4>,
    mut output: Output<Vec4>,
) {
```

### CODE REVIEW

**Comment by repi** [comment]
@Mergifyio rebase

**Review by Jasper-Bekkers — CHANGES_REQUESTED** [review]
Maybe you already incorporated this feedback I gave in the discord but I couldn't find it in the PR.

>alright yeah then it's fine; just in case it might be worth while to reserve descriptor set 0 for our use, that way we can auto-gen id's at least into set 0 and avoid potential clashes while we transition over the the actual binding model

**Comment by XAMPPRocky** [comment]
With the refactor, would it be possible to also add a chapter in the `rust-gpu` dev guide that lists these attributes and their basic behaviour?

**Comment by khyperia** [comment]
> Maybe you already incorporated this feedback I gave in the discord but I couldn't find it in the PR.

Oh, I missed this comment, I thought we decided with the explicit system seeing as it's the most flexible _and_ easiest solution. I don't think putting extra effort into making it clean is worth it, that effort should be put into the bindings rfc implementation.

**Review by Jasper-Bekkers — APPROVED** [review]

**Comment by khyperia** [comment]
uuh, that was not supposed to be merged, there were still reviews pending?!?

**Pull request merged**
