### PR TITLE
Always emit json metadata, and emit entry point names

### LINKED ISSUE #620: Always emit json, even for non-multimodule, and embed metadata in the json
We discussed this in the meeting on May 6th, but I want to write it down and assign it to me so I can track it/remember it.

tl;dr we want to do a whole host of stuff (emitting entry point names as string constants in CPU-side codegen, doing CPU-side static asserts for entry point interface struct layout, etc.) that requires passing metadata about the shader out of the compiler and back into the consumer of spirv-builder (so it can do CPU-side codegen). A nice, clean, easy way of passing that metadata back is to use our lil json system we invented for multimodule, and always use it, and embed extra shenanigans into that json.

### PR DESCRIPTION
**Pull request by khyperia**
Fixes #620

### CODE REVIEW

**Review by VZout — APPROVED** [review]
Awesome! and looks quite easy to add interface variables as well to the metadata. But this does not work with non-multimodule?

**Comment by khyperia** [comment]
> But this does not work with multimodule?

yeah, it does work? `cargo run -p multibuilder` outputs this:

```
CompileResult {
    module: MultiModule(
        {
            "main_fs": "/home/khyperia/me/rust-gpu/target/spirv-unknown-spv1.3/release/deps/sky_shader.spv.dir/main_fs",
            "main_vs": "/home/khyperia/me/rust-gpu/target/spirv-unknown-spv1.3/release/deps/sky_shader.spv.dir/main_vs",
        },
    ),
    entry_points: [
        "main_fs",
        "main_vs",
    ],
}
```

the code does take a little shortcut and yoinks the entrypoint out of the precomputed dictionary (which itself yoinks the entrypoint out of the module) instead of digging around in the module itself, because it's a bit simpler code, but it could easily be expanded to dig through the modules themselves if we wanted to extract more metadata (or carry information through the compiler and emit it, instead of reflecting the output)

**Comment by VZout** [comment]
Ah I saw this and thought metadata was disabled in its entirety for multimodule.
```
if self.print_metadata && self.multimodule {
    return Err(SpirvBuilderError::MultiModuleWithPrintMetadata);
}
```

**Comment by khyperia** [comment]
Ah, that's printing cargo metadata, and is no change in behavior from the current system - it already produces the same error before this PR. "Metadata" in the context of that code means things like printing `cargo:rerun-if-changed=blah` to stdout.

**Pull request merged**
