### PR TITLE
Update to glam 0.20

### PR DESCRIPTION
**Pull request by emilk**
When it comes to dependencies, it takes all the running you can do to keep in the same place.

### CODE REVIEW

**Comment by hrydgard** [comment]
glam is broken for rust-gpu in the 0.20.x releases before 0.20.2, not sure if worth trying to specify the range more exactly?

**Comment by repi** [comment]
Oh good catch, then specifying the exact minimum patch version should solve that.  And it will only allow version of that or above. hopefully works out

**Comment by emilk** [comment]
So ideally we would allow all version in the `0.17`-`0.19` range PLUS `0.20.2`, but I don't think cargo supports specifying multiple allowed ranges like that: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

The alternative is changing it to just `0.20.2`, but that means dropping support for glam `0.17`-`0.19`.

**Comment by repi** [comment]
Oh ouch, that does indeed sound like a limitation of cargos version comparison, and a fair workaround with the patch version.

**Review by hrydgard — APPROVED** [review]

**Review by khyperia — APPROVED** [review]
Yay! CI tests with `Cargo.lock`, which was still at 0.19 - so I quick pushed a `cargo update` to make sure everything's tidy with 0.20.

**Comment by khyperia** [comment]
ugh, `cargo fetch --locked` stalled for an hour and a half in the lint CI step, I cancelled that but github has no option for "just rerun these things" and had to rerun everything. Now, the ubuntu CI step is also stalled for an hour and a half on `cargo fetch --locked`. I'm just going to force-merge because everything has been green, just not all on the same CI run.

**Pull request merged**
