### PR TITLE
feat: implemented swap chain recreation #103

### PR DESCRIPTION
**Pull request by jirislav**
As requested in #103

### CODE REVIEW

**Comment by expenses** [comment]
Here's a fix for what you encountered in https://github.com/EmbarkStudios/rust-gpu/issues/103#issuecomment-715665816:
```diff
diff --git a/examples/example-runner/src/main.rs b/examples/example-runner/src/main.rs
index 7ca6bc1..99f4858 100644
--- a/examples/example-runner/src/main.rs
+++ b/examples/example-runner/src/main.rs
@@ -200,8 +200,8 @@ pub struct ExampleBase {
 }

 impl ExampleBase {
-    pub fn render_loop<T, F: Fn(&Self) + 'static>(
-        self,
+    pub fn render_loop<T, F: Fn(&mut Self) + 'static>(
+        mut self,
         events_loop: winit::event_loop::EventLoop<T>,
         f: F,
     ) -> ! {
@@ -209,7 +209,7 @@ impl ExampleBase {
         use winit::event_loop::*;
         events_loop.run(move |event, _window_target, control_flow| match event {
             Event::RedrawEventsCleared { .. } => {
-                f(&self);
+                f(&mut self);
             }
             Event::WindowEvent { event, .. } => match event {
                 WindowEvent::KeyboardInput { input, .. } => {
```

**Comment by jirislav** [comment]
> Here's a fix for what you encountered in [#103 (comment)](https://github.com/EmbarkStudios/rust-gpu/issues/103#issuecomment-715665816):
> 
> ```diff
> diff --git a/examples/example-runner/src/main.rs b/examples/example-runner/src/main.rs
> index 7ca6bc1..99f4858 100644
> --- a/examples/example-runner/src/main.rs
> +++ b/examples/example-runner/src/main.rs
> @@ -200,8 +200,8 @@ pub struct ExampleBase {
>  }
> 
>  impl ExampleBase {
> -    pub fn render_loop<T, F: Fn(&Self) + 'static>(
> -        self,
> +    pub fn render_loop<T, F: Fn(&mut Self) + 'static>(
> +        mut self,
>          events_loop: winit::event_loop::EventLoop<T>,
>          f: F,
>      ) -> ! {
> @@ -209,7 +209,7 @@ impl ExampleBase {
>          use winit::event_loop::*;
>          events_loop.run(move |event, _window_target, control_flow| match event {
>              Event::RedrawEventsCleared { .. } => {
> -                f(&self);
> +                f(&mut self);
>              }
>              Event::WindowEvent { event, .. } => match event {
>                  WindowEvent::KeyboardInput { input, .. } => {
> ```

thank you, I didn't think about the callback definition, that solves my problem :)

And to my surprise, the rest of code actually handles the `ERROR_OUT_OF_DATE_KHR` panic, the window doesn't crash on a resize event anymore (maximize / unmaximize / minize using the window buttons).

But I see there is another bug, when I drag the window border to apply a manual resize (or double click the window title), I get error `Failed to unfocus input context: XError { description: "BadDrawable (invalid Pixmap or Window parameter)", error_code: 9, request_code: 149, minor_code: 4 }`.
- it's hard for me to say whether or not it should be solved in #103 or another issue should be created?
- note that I'm new to the GPU world, so I can't really say as what the problem could be :shrug:

**Comment by XAMPPRocky** [comment]
@jirislav Thank you for your PR! I think you need to rebase your changes with the latest main to get CI to pass.

**Comment by khyperia** [comment]
Also just a warning that if https://github.com/EmbarkStudios/rust-gpu/pull/109 merges first, this will presumably have lots of conflicts

**Comment by jirislav** [comment]
> Also just a warning that if #109 merges first, this will presumably have lots of conflicts

Thanks for the heads up. I think I'm going to wait for it to merge and then redo my work on wgpu sample :slightly_smiling_face:

**Comment by termhn** [comment]
@jirislav #109 is in, I'll be happy to review and merge this when you get a chance to rebase or rewrite it on top of that :)

**Comment by khyperia** [comment]
I believe this has been done by https://github.com/EmbarkStudios/rust-gpu/pull/299, but thanks for your work here!

**Pull request closed without merging**
